### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 36: invalid continuation byte

### ISSUE THREAD

**Issue by huaji0353** [KirkSuD/osudb#1]
20191106 version fix

Size in bytes of the beatmap entry. Only present if version is less than 20191106.

osudb.py line 96 
beatmap_data_types = remove top 'Int'

beatmap_data_types = ['String', 'String', 'String', 'String', 'String', 'String', 'String', 'String', 'String', 'Byte', 'Short', 'Short', 'Short', 'Long', 'Single', 'Single', 'Single', 'Single', 'Double', 'Int-Double pair*', 'Int-Double pair*', 'Int-Double pair*', 'Int-Double pair*', 'Int', 'Int', 'Int', 'Timing point+', 'Int', 'Int', 'Int', 'Byte', 'Byte', 'Byte', 'Byte', 'Short', 'Single', 'Byte', 'String', 'String', 'Short', 'String', 'Boolean', 'Long', 'Boolean', 'String', 'Long', 'Boolean', 'Boolean', 'Boolean', 'Boolean', 'Boolean', 'Int', 'Byte']

**Comment by huaji0353** [comment]
[osudb.py.txt](https://github.com/KirkSuD/osudb/files/4550414/osudb.py.txt)

**Comment by KirkSuD** [comment]
Thank you for opening this issue.
I just pushed a quick fix for it.

**Comment by KirkSuD** [comment]
TODO: generate a better error message to notify where the error occurrs,
 to react more quickly when osu! changes DB format.
Tracing the whole DB format by hand may take some time.

TODO: 更好的錯誤回報，這樣osu!改格式時才不用整個重看。
