### ISSUE TITLE
Parser always returning True For perfect combo (scores.db)

### ISSUE THREAD

**Issue by Mrcubix** [KirkSuD/osudb#2]
While making a serializer, i've identified an issue with my parsed data, every Boolean for Perfect combo are true even though i didn't FC the map at all, i can't seem to identify the issue in your code myself, and only found out after comparing the parsed bytes directly in a txt file and then comparing the result comparing the result between the original and the serialized db

[Parser_issue.zip](https://github.com/KirkSuD/osudb/files/5760775/Parser_issue.zip)

**Comment by KirkSuD** [comment]
Hello, I found the bug. It is stupid, I missed `[0]` in `def parse_type(fobj, data_type):`
`return bool(fobj.read(1))` -> `return bool(fobj.read(1)[0])`.

I added a hard-coded serializer to check there's no other bug.
It's just like the inverse of the parser. Though nasty, it successfully serialized my DBs to the original.
(If you've made one, please use yours; I think this is dirty code)

Sorry for not responding your mail. I thought hard-coding the serializer isn't good.
I wanted to rewrite the whole code, but I postponed again and again... until I received this bug issue.

I don't actively play osu! anymore. But being able to read the DBs is still good for me.
So, I may still rewrite one. Maybe in Kaitai Struct?
There are too many different language of osu! parser / serializer online: JS, C#, Rust...
[Kaitai Struct](https://kaitai.io/) is language neutral, looks pretty good.

**Comment by Mrcubix** [comment]
I've replaced the function with a normal struct.ynpack one that work, i've been working on this serializer for a month now after getting stuck wondering how i was going to proceed, but now, the only thing left is to serialize the strlen by endoing an unsigned int, which is going to a while since i've yet to understand `set high order bit of byte;` anyway, thanks for answering me

**Comment by KirkSuD** [comment]
Okay, [ULEB128 part of my code is here](https://github.com/KirkSuD/osudb/blob/master/osudb.py#L155).

And I'll close this issue later, because the issue seems to be fixed.
